---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Load data from internet

```{r}
my.url <- url("http://people.whitman.edu/~hundledr/courses/M250F03/LynxHare.txt")
```


```{r}
lynx_vs_hares <- read.table(my.url,
                            header = FALSE,
                            col.names = c("year","N.lynx", "N.hare"))

```

## Base R plot

```{r}
plot(N.lynx ~ year, data = lynx_vs_hares, type = "l")
lines(N.hare ~ year, data = lynx_vs_hares, type = "l", col = 2, lty = 2)
```


## ggpubr - have to stack it

write function - stack data

```{r}
stack_data <- function(df, 
                       x.col.name,
                       y1.col.name, 
                       y2.col.name, 
                       ystack.col.name = "stacked",
                       y1.label = "group1",
                       y2.label = "group2"){
  n.row <- dim(df)[1]
  x <- df[,x.col.name]
  y1 <- df[,y1.col.name]
  y2 <- df[,y2.col.name]
  y1.lab <- rep(y1.label, n.row)
  y2.lab <- rep(y2.label, n.row)
  
  df.new <- data.frame(x = rep(x,2),
                       y = c(y1,y2),
                       group.num = c(rep(1,n.row),
                                      rep(2,n.row)),
                       group.name = c(y1.lab, y2.lab))
  names(df.new)[1:2] <- c(x.col.name,
                     ystack.col.name)
  
  return(df.new)
                       }
```


```{r}
names(lynx_vs_hares)
out <- stack_data(df = lynx_vs_hares,
           x.col.name = "year",
           y1.col.name = "N.lynx",
           y2.col.name = "N.hare",
           ystack.col.name = "N",
           y1.label = "lynx",
           y2.label = "hare")
```


