# Reading - plots (Navarro chapter 6)
Please read the indicated sections of Chapter 6 of Navarro's R book and run the code. 

This listed as OPTIONAL truly are optional - I recommend skipping them, but if you're curious you can take a look.

You can generate some data to plot using this line of code

afl.margins <- c(56,31,56,8,32,14,36,56,9,1,3 ,104,43,44,72,9,28,56,31,56,89,31,11,32,51,19,11,13 ,14,4,14,72,19,28)
 

There are many sections of this chapter you can skip, either because we won't use the commands or they focus only on statistics concepts.

You can download the book here or find the HTML version:

https://learningstatisticswithr.com/ (Links to an external site.)

HTML version: https://learningstatisticswithr.com/book/ (Links to an external site.)

(note that the HTML version doesn't have page numbers)

A PDF copy with key sections highlighted is on Box.

 

6. Drawing graphs

6.1 An overview of R graphics

6.2 An introduction to plotting
6.2.2 Customising the title and the axis labels
(OPTIONAL - we'll get more into this later)
6.2.3 Changing the plot type
6.2.4 Changing other features of the plot
(OPTIONAL - we'll get more into this later)
6.2.5 Changing the appearance of the axes (
(OPTIONAL - we'll get more into this later)
6.2.6 Don't panic
6.3 Histograms

You can generate some data to plot using this line of code

afl.margins <- c(56,31,56,8,32,14,36,56,9,1,3 ,104,43,44,72,9,28,56,31,56,89,31,11,32,51,19,11,13 ,14,4,14,72,19,28)
Focus on just the first line of code

hist( afl.margins )
The other stuff is optional

6.3.1 Visual style of your histogram (OPTIONAL)
6.5 Boxplots

Run the basic boxplot() command and read the first part of this section

6.5.1 Visual style of your boxplot (OPTIONAL)
6.6 Scatterplots

Focus on just the material on page 184.

You can practice making scatter plots using this code:

x <- 1:100 
y <- x*2+ rnorm(100,0,20)
plot(y ~ x)
plot(x, y)

6.9 Summary
