# Reading - Descriptive stats (Navarro chapter 5)
Please read the indicated sections of Chapter 5 of Navarro's R book and run the code. 

You can focus just on learning the commands.  If you have not had much exposure on the topic of descriptive statistics or are rusty, you can read more deeply about the concepts.

 

To test the commands in the book you can generate some data using this line of code:

afl.margins <- c(56,31,56,8,32,14,36,56,9,1,3 ,104,43,44,72,9,28)
afl.finalists <- c("Hawthorn", "Melbourne", "Carlton", "Melbourne ", "Hawthorn","Carlton", "Melbourne", "Carlton" ,"Hawthorn", "Melbourne")

Don't bother actually loading the data set mentioned in the book.

 

There are many sections of this chapter you can skip, either because we won't use the commands or they focus only on statistics concepts.

You can download the book here or find the HTML version:

https://learningstatisticswithr.com/ (Links to an external site.)

HTML version: https://learningstatisticswithr.com/book/ (Links to an external site.)

(note that the HTML version doesn't have page numbers)

A PDF copy with key sections highlighted is on Box.

 

5. Descriptive statistics

5.1 Measures of central tendency

5.1.2 Calculating the mean in R
5.1.3 The median

5.1.7 Mode

Don't worry about the modeOf() and maxFreq() function
5.2 Measures of variability

5.2.1 Range
5.2.4 Variance
Focus on code, not the concepts
5.2.5 Standard deviation

5.4 Getting an overall summary of a variable

For the summary command you can practice by running this code

df <- data.frame(x = 1:20, y = 20:1)

5.4.1 "Summarising" a variable
5.4.2 Summarising" a data frame

5.8 Handling missing values

5.8.1 The single variable case
5.9 Summary
